#!/bin/bash

DEFAULT_GPUS_PER_NODE=1
DEFAULT_MASTER_ADDR="127.0.0.1"
DEFAULT_MASTER_PORT=25001

RUN_NAME=${RUN_NAME:-$DEFAULT_RUN_NAME}
OUTPUT_DIR=${OUTPUT_DIR:-"runs/train/$RUN_NAME"}

# ✅ DO NOT override if already set
export WANDB_ENTITY=${WANDB_ENTITY:-"fyp-21"}
export WANDB_PROJECT=${WANDB_PROJECT:-"vila"}
export WANDB_DIR=$OUTPUT_DIR
export WANDB_RUN_ID=$RUN_NAME
export WANDB_NAME=${WANDB_NAME:-$RUN_NAME}
export WANDB_RESUME="allow"

NNODES=${SLURM_JOB_NUM_NODES:-1}
NODE_RANK=${SLURM_PROCID:-0}
GPUS_PER_NODE=${SLURM_JOB_GPUS_PER_NODE:-$DEFAULT_GPUS_PER_NODE}

MASTER_ADDR=${MASTER_ADDR:-$DEFAULT_MASTER_ADDR}
MASTER_PORT=${MASTER_PORT:-$DEFAULT_MASTER_PORT}

GLOBAL_TRAIN_BATCH_SIZE=${GLOBAL_TRAIN_BATCH_SIZE:-$DEFAULT_GLOBAL_TRAIN_BATCH_SIZE}
GRADIENT_ACCUMULATION_STEPS=${GRADIENT_ACCUMULATION_STEPS:-$DEFAULT_GRADIENT_ACCUMULATION_STEPS}

PER_DEVICE_TRAIN_BATCH_SIZE=$((GLOBAL_TRAIN_BATCH_SIZE / NNODES / GPUS_PER_NODE / GRADIENT_ACCUMULATION_STEPS))

export NCCL_IB_SL=1
export CUDA_DEVICE_MAX_CONNECTIONS=1
export TORCH_NCCL_ASYNC_ERROR_HANDLING=1
export OMP_NUM_THREADS=1
